//Define the various control inputs as well as buttons
#ifndef CONTROLS
#define CONTROLS
enum controls_t
{
CONTROLLER_KEYBOARD = 1,
CONTROLLER_WIIMOTE,
CONTROLLER_NUNCHUK,
CONTROLLER_CLASSIC,
CONTROLLER_GAMECUBE,
CONTROLLER_MOUSE,
CONTROLLER_POINTER,
CONTROLLER_JOYSTICK,
CONTROLLER_NONE
};
enum buttons_t
{
B_LEFT = 1,
B_RIGHT,
B_UP,
B_DOWN,
BUTTON_1,
BUTTON_2,
BUTTON_MENU,
BUTTON_LEVEL_NEXT,
BUTTON_LEVEL_PREV,
B_ANY,
BUTTON_LEFT_CLICK,
BUTTON_RIGHT_CLICK,
BUTTON_MOUSEWHEEL,
INPUT_NONE
};
#define MAX_JOYSTICK 4
#endif