struct Mix_Chunk;
extern Mix_Chunk *snd_explode;
extern Mix_Chunk *snd_switch;
extern Mix_Chunk *snd_teleport;
extern Mix_Chunk *snd_spring;
extern Mix_Chunk *snd_splash;
extern Mix_Chunk *snd_zap;
extern Mix_Chunk *snd_smash;
extern Mix_Chunk *snd_burn;
extern Mix_Chunk *snd_ignite;
extern Mix_Chunk *snd_freeze;
extern Mix_Chunk *snd_melt;
extern Mix_Chunk *snd_crystalBreak;
extern Mix_Music *levelSelectMusic;
extern Mix_Chunk *snd_barrierOpen;
extern Mix_Chunk *snd_duplicate;
bool playSound(Mix_Chunk *input);
void musicInit();
void setPanning(unsigned int channel, unsigned int right);
Mix_Music* loadMusic(char *fileName);
extern Mix_Music *titleMusic;
void freeMusic(int levelNum);
void playMusic(int levelNum);
void playMusic(Mix_Music *music);
void freeAllMusic();
void freeSound();